import './globals.css'
import { Saira } from 'next/font/google'

const saira = Saira({
  weight: ['300', '400', '500', '600'],
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout =({
  children,
}: {
  children: React.ReactNode
}) => {
  return (
    <html lang="en">
      <body className={saira.className}>{children}</body>
    </html>
  )
}

export default RootLayout
